import {registerUser,loginUser,logoutUser,watchAuth,getUserProfile,watchUserProfile,updateUserProfile,uploadProfileMedia,uploadFile,deleteOwnAccount,findUsers,getUsers,watchUsers,createPost,updatePostText,deletePost,reportContent,watchPosts,toggleReaction,getMyReaction,savePostView,getPostInsights,addComment,watchComments,sendFriendRequest,getFriendStatus,getIncomingRequests,watchIncomingRequests,respondFriendRequest,createStory,updateStoryText,deleteStory,watchStories,saveStoryView,getStoryInsights,sendMessage,watchMessages,getChatPeople,isFollowing,toggleFollow,createChannel,getChannels,watchChannels,createCommunity,getCommunities,watchCommunities,joinCommunity} from "./firebase.js";

let currentUser=null,currentProfile=null,selectedUser=null,selectedChatUser=null,unsubscribePosts=null,unsubscribeStories=null,unsubscribeMessages=null,unsubscribeUsers=null,unsubscribeRequests=null,unsubscribeChannels=null,unsubscribeCommunities=null,unsubscribeProfile=null,commentListeners={},lastPageBeforeUserProfile="home",accountDeletionInProgress=false;
const KRONO_DATA_SAVER_KEY="kronoDataSaver";
const dataSaverEnabled=()=>localStorage.getItem(KRONO_DATA_SAVER_KEY)!=="false";
function svgIcon(name){const paths={
 home:'<path d="M3 10.5 12 3l9 7.5"/><path d="M5 9.5V21h14V9.5"/><path d="M9 21v-6h6v6"/>',
 users:'<circle cx="9" cy="8" r="3"/><path d="M3 20c.6-3.2 2.5-5 6-5s5.4 1.8 6 5"/><circle cx="17" cy="9" r="2.3"/><path d="M15 15.2c2.6.2 4.2 1.7 4.7 4"/>',
 plus:'<path d="M12 5v14M5 12h14"/>',
 message:'<path d="M4 5.5h16v10H8l-4 4v-14Z"/>',
 profile:'<circle cx="12" cy="7" r="3.2"/><path d="M5 21c.7-4 3-6 7-6s6.3 2 7 6"/>',
 heart:'<path d="M20.8 8.8c0 5.3-8.8 10.2-8.8 10.2S3.2 14.1 3.2 8.8A4.7 4.7 0 0 1 12 6.1a4.7 4.7 0 0 1 8.8 2.7Z"/>',
 comment:'<path d="M4 5.5h16v10H8l-4 4v-14Z"/>',
 bookmark:'<path d="M6 4h12v17l-6-4-6 4V4Z"/>',
 share:'<path d="M4 12h12"/><path d="m12 6 6 6-6 6"/><path d="M18 12h1a2 2 0 0 1 2 2v4"/>',
 eye:'<path d="M2.5 12s3.2-5 9.5-5 9.5 5 9.5 5-3.2 5-9.5 5-9.5-5-9.5-5Z"/><circle cx="12" cy="12" r="2.5"/>',
 search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
 bell:'<path d="M6 17h12l-1.4-2V10a4.6 4.6 0 0 0-9.2 0v5L6 17Z"/><path d="M10 20h4"/>',
 menu:'<path d="M4 7h16M4 12h16M4 17h16"/>',
 image:'<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8" cy="9" r="1.5"/><path d="m4 17 5-5 4 4 2-2 6 5"/>',
 camera:'<path d="M4 7h4l1.5-2h5L16 7h4v12H4V7Z"/><circle cx="12" cy="13" r="3.5"/>',
 phone:'<path d="M7.2 4.5 4.8 6.2c-.7.5-.9 1.4-.6 2.2 1.8 4.8 5.6 8.6 10.4 10.4.8.3 1.7.1 2.2-.6l1.7-2.4c.4-.6.3-1.4-.3-1.8l-2.4-1.6c-.5-.3-1.2-.3-1.6.2l-1 1.1c-2-1-3.7-2.7-4.7-4.7l1.1-1c.5-.4.5-1.1.2-1.6L9 4.8c-.4-.6-1.2-.7-1.8-.3Z"/>',
video:'<rect x="3" y="6" width="13" height="12" rx="2"/><path d="m16 10 5-3v10l-5-3V10Z"/>',
settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.8 1.8 0 0 0 .3 2l.1.1-1.8 1.8-.1-.1a1.8 1.8 0 0 0-2-.3 1.8 1.8 0 0 0-1 1.6V20h-2.6v-.1a1.8 1.8 0 0 0-1-1.6 1.8 1.8 0 0 0-2 .3l-.1.1-1.8-1.8.1-.1a1.8 1.8 0 0 0 .3-2 1.8 1.8 0 0 0-1.6-1H6v-2.6h.1a1.8 1.8 0 0 0 1.6-1 1.8 1.8 0 0 0-.3-2l-.1-.1 1.8-1.8.1.1a1.8 1.8 0 0 0 2 .3 1.8 1.8 0 0 0 1-1.6V4h2.6v.1a1.8 1.8 0 0 0 1 1.6 1.8 1.8 0 0 0 2-.3l.1-.1 1.8 1.8-.1.1a1.8 1.8 0 0 0-.3 2 1.8 1.8 0 0 0 1.6 1h.1v2.6h-.1a1.8 1.8 0 0 0-1.6 1Z"/>',
play:'<rect x="4" y="4" width="16" height="16" rx="3"/><path d="m10 8 6 4-6 4Z"/>',
 attach:'<path d="M20 11.5 11.5 20a5 5 0 0 1-7-7l8.5-8.5a3.5 3.5 0 0 1 5 5L9.5 18a2 2 0 0 1-3-3l8-8"/>' ,emoji:'<circle cx="12" cy="12" r="9"/><circle cx="9" cy="10" r=".7" fill="currentColor"/><circle cx="15" cy="10" r=".7" fill="currentColor"/><path d="M8 14c1.2 1.6 2.8 2.3 4 2.3s2.8-.7 4-2.3"/>' ,mic:'<path d="M12 15a3 3 0 0 0 3-3V7a3 3 0 0 0-6 0v5a3 3 0 0 0 3 3Z"/><path d="M5.5 12a6.5 6.5 0 0 0 13 0M12 18.5V22M9 22h6"/>' ,send:'<path d="m3 11 18-8-5 18-4.5-7.5L3 11Z"/><path d="m11.5 13.5 4-4"/>' ,more:'<circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/>'};return `<svg class="arlo-svg" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${paths[name]||paths.more}</svg>`}


document.addEventListener("DOMContentLoaded",()=>{setTimeout(()=>document.getElementById("splash")?.classList.add("hide"),1800);document.getElementById("registerPassword")?.addEventListener("input",checkPassword);document.getElementById("storyMedia")?.addEventListener("change",previewStory);document.getElementById("storyAudio")?.addEventListener("change",e=>{document.getElementById("audioName").textContent=e.target.files[0]?.name||"";previewStory()});watchAuth(async u=>{if(u){currentUser=u;await showApp()}else{currentUser=null;showAuth()}})});

function showAuth(){document.getElementById("auth").classList.remove("hidden");document.getElementById("app").classList.add("hidden")}
async function showApp(){document.getElementById("auth").classList.add("hidden");document.getElementById("app").classList.remove("hidden");currentProfile=await getUserProfile(currentUser.uid);if(!currentProfile){await logoutUser().catch(()=>{});return}fillProfile();if(unsubscribeProfile)unsubscribeProfile();unsubscribeProfile=watchUserProfile(currentUser.uid,async profile=>{if(profile){currentProfile=profile;fillProfile();return}if(accountDeletionInProgress)return;accountDeletionInProgress=true;currentProfile=null;[unsubscribePosts,unsubscribeStories,unsubscribeUsers,unsubscribeRequests,unsubscribeChannels,unsubscribeCommunities].forEach(fn=>{try{fn?.()}catch{}});unsubscribePosts=unsubscribeStories=unsubscribeUsers=unsubscribeRequests=unsubscribeChannels=unsubscribeCommunities=null;document.getElementById("app")?.classList.add("hidden");alert("تم حذف حسابك من Firebase، وسيتم تسجيل خروجك من KRONO.");await logoutUser().catch(()=>{});accountDeletionInProgress=false},()=>{});if(!unsubscribePosts)unsubscribePosts=watchPosts(renderPosts,e=>{console.error("Arlo posts listener error:",e);const c=document.getElementById("posts");if(c)c.innerHTML='<div class="post">تعذر تحميل المنشورات من Firebase. إذا ظهر ERR_BLOCKED_BY_CLIENT جرّب تعطيل مانع الإعلانات/حماية التتبع للصفحة ثم أعد التحميل.</div>';});if(!unsubscribeStories)unsubscribeStories=watchStories(renderStories);if(!unsubscribeUsers)unsubscribeUsers=watchUsers(users=>{window.__kronoUsers=users;loadExplore(users).catch(console.error);if(selectedUser){const fresh=users.find(u=>u.uid===selectedUser.uid);if(!fresh){selectedUser=null;document.getElementById("otherProfilePage")?.classList.add("hidden");openPage("home")}else selectedUser=fresh}});if(!unsubscribeRequests)unsubscribeRequests=watchIncomingRequests(currentUser.uid,renderNotifications);if(!unsubscribeChannels)unsubscribeChannels=watchChannels(items=>{window.__kronoChannels=items;renderChannels(items)});if(!unsubscribeCommunities)unsubscribeCommunities=watchCommunities(items=>{window.__kronoCommunities=items;renderCommunities(items)});loadExplore(window.__kronoUsers||[]);renderNotifications([])}
function applyDataSaverUI(){const on=dataSaverEnabled();document.body.classList.toggle("data-saver",on);const b=document.getElementById("dataSaverBanner");if(b)b.innerHTML=on?"📶 وضع توفير البيانات <span>مفعّل</span>":"⚡ الوضع الكامل <span>توفير البيانات متوقف</span>"}
window.toggleDataSaver=()=>{localStorage.setItem(KRONO_DATA_SAVER_KEY,String(!dataSaverEnabled()));applyDataSaverUI();alert(dataSaverEnabled()?"✓ تم تفعيل توفير البيانات":"✓ تم إيقاف توفير البيانات")};

function renderVideoCard(p,compact=false){return `<article class="video-card" data-video-id="${esc(p.id)}"><div class="video-thumb"><video src="${esc(p.mediaUrl)}" controls playsinline preload="none"></video></div><div class="video-card-body"><strong>${esc(p.name||"مستخدم Arlo")}</strong>${p.text?`<p>${esc(p.text)}</p>`:""}<small>👁️ ${p.viewsCount||0} · ❤️ ${p.likesCount||0}</small></div></article>`}
window.renderShorts=()=>{const c=document.getElementById("shortsList");if(!c)return;const videos=(window.__kronoPosts||[]).filter(p=>p.mediaType==="video");c.innerHTML=videos.length?videos.map(p=>renderVideoCard(p)).join(""):"<div class='post'>لا توجد فيديوهات قصيرة حاليًا. انشر أول فيديو في Arlo.</div>";applyDataSaverUI()};
window.renderWatch=()=>{const c=document.getElementById("watchList");if(!c)return;const videos=(window.__kronoPosts||[]).filter(p=>p.mediaType==="video");c.innerHTML=videos.length?videos.map(p=>renderVideoCard(p,true)).join(""):"<div class='post'>لا توجد فيديوهات متاحة حاليًا.</div>";applyDataSaverUI()};
async function renderChannels(items=null){const c=document.getElementById("channelsList");if(!c)return;try{items=items||window.__kronoChannels||await getChannels();c.innerHTML=items.length?items.map(x=>`<div class='hub-card'><div class='hub-icon'>📣</div><h3>${esc(x.name)}</h3><p>${esc(x.description||"قناة Arlo")}</p><small>بواسطة ${esc(x.ownerName||"مستخدم")}</small></div>`).join(""):"<div class='post'>لا توجد قنوات بعد. أنشئ أول قناة.</div>"}catch(e){c.innerHTML="<div class='post'>تعذر تحميل القنوات.</div>"}}
async function renderCommunities(items=null){const c=document.getElementById("communitiesList");if(!c)return;try{items=items||window.__kronoCommunities||await getCommunities();c.innerHTML=items.length?items.map(x=>`<div class='hub-card'><div class='hub-icon'>👥</div><h3>${esc(x.name)}</h3><p>${esc(x.description||"مجتمع Arlo")}</p><small>👥 ${x.membersCount||1} أعضاء</small><button class='secondary-btn' onclick="joinKronoCommunity('${x.id}')">انضمام</button></div>`).join(""):"<div class='post'>لا توجد مجتمعات بعد. أنشئ أول مجتمع.</div>"}catch(e){c.innerHTML="<div class='post'>تعذر تحميل المجتمعات.</div>"}}
window.createKronoChannel=async()=>{const name=prompt("اسم القناة:");if(!name?.trim())return;const desc=prompt("وصف القناة:","")||"";try{await createChannel(currentUser,name.trim(),desc);renderChannels();alert("✓ تم إنشاء القناة")}catch(e){alert("تعذر إنشاء القناة: "+(e.message||""))}};
window.createKronoCommunity=async()=>{const name=prompt("اسم المجتمع:");if(!name?.trim())return;const desc=prompt("وصف المجتمع:","")||"";try{await createCommunity(currentUser,name.trim(),desc);renderCommunities();alert("✓ تم إنشاء المجتمع")}catch(e){alert("تعذر إنشاء المجتمع: "+(e.message||""))}};
window.joinKronoCommunity=async id=>{try{await joinCommunity(id,currentUser.uid);alert("✓ انضممت للمجتمع");renderCommunities()}catch(e){alert("تعذر الانضمام للمجتمع.")}};
window.toggleUserFollow=async uid=>{try{const on=await toggleFollow(currentUser.uid,uid);const b=document.getElementById("otherPageFollowButton");if(b)b.textContent=on?"✓ متابَع":"＋ متابعة"}catch(e){alert(e.message||"تعذر تحديث المتابعة.")}};

function setText(id,value){const el=document.getElementById(id);if(el)el.textContent=value??""}
function fillProfile(){if(!currentProfile)return;const name=currentProfile.name||"مستخدم Arlo",initial=name[0]||"K";setText("welcomeName",`أهلاً ${name} 👋`);setText("profileName",name);const profileNameEl=document.getElementById("profileName");if(profileNameEl)profileNameEl.innerHTML=esc(name)+verifiedBadge(currentUser?.uid);setText("profileUsername",currentProfile.username?`@${currentProfile.username}`:"");setText("profileEmail",currentProfile.publicEmail?(currentProfile.email||""):"البريد الإلكتروني مخفي");setText("profileBio",currentProfile.bio||"عضو في Arlo");setText("profileFriends",currentProfile.friendsCount||0);setText("profilePosts",currentProfile.postsCount||0);setProfileImage("profileAvatar",currentProfile.avatarUrl,initial);setProfileImage("homeAvatar",currentProfile.avatarUrl,initial);setProfileImage("bottomProfileAvatar",currentProfile.avatarUrl,initial);const cover=document.querySelector('#profilePage .profile-cover');if(cover)cover.style.backgroundImage=currentProfile.coverUrl?`url("${esc(currentProfile.coverUrl)}")`:"";const birth=document.getElementById("profileBirth");if(birth)birth.textContent=currentProfile.birth?`🎂 ${currentProfile.birth}`:""}
function setProfileImage(id,url,fallback){const el=document.getElementById(id);if(!el)return;if(url){el.innerHTML=`<img src="${esc(url)}" alt="صورة الملف" loading="lazy">`;el.classList.add('has-image')}else{el.textContent=fallback;el.classList.remove('has-image')}}

window.showLogin=()=>{document.getElementById("loginPage").classList.remove("hidden");document.getElementById("registerPage").classList.add("hidden")};window.showRegister=()=>{document.getElementById("loginPage").classList.add("hidden");document.getElementById("registerPage").classList.remove("hidden")};window.togglePassword=id=>{const x=document.getElementById(id);x.type=x.type==="password"?"text":"password"};
function checkPassword(){const p=document.getElementById("registerPassword").value,h=document.getElementById("passwordHint");const strong=p.length>=8&&/[A-Za-zأ-ي]/.test(p)&&/[0-9]/.test(p)&&/[^A-Za-zأ-ي0-9]/.test(p);h.textContent=!p?"":strong?"✓ كلمة السر قوية":"8 أحرف + حروف + أرقام + رمز";h.style.color=strong?"var(--main)":"var(--danger)"}
window.createAccount=async()=>{const g=id=>document.getElementById(id).value.trim();const name=g("registerName"),username=g("registerUsername"),email=g("registerEmail"),phone=g("registerPhone"),birth=document.getElementById("registerBirth").value,gender=document.getElementById("registerGender").value,password=g("registerPassword"),confirm=g("registerConfirm");if(!name||!username||!email||!birth||!gender||!password||!confirm)return alert("أكمل جميع البيانات.");if(password!==confirm)return alert("كلمتا السر غير متطابقتين.");if(!(password.length>=8&&/[A-Za-zأ-ي]/.test(password)&&/[0-9]/.test(password)&&/[^A-Za-zأ-ي0-9]/.test(password)))return alert("كلمة السر ضعيفة.");try{await registerUser(name,username,email,password,phone,birth,gender);alert("🎉 تم إنشاء حساب Arlo!")}catch(e){alert(firebaseError(e))}};
window.login=async()=>{const email=document.getElementById("loginEmail").value.trim(),password=document.getElementById("loginPassword").value;if(!email||!password)return alert("أدخل البريد وكلمة السر.");try{await loginUser(email,password)}catch(e){alert(firebaseError(e))}};
window.openPostEditor=()=>{const m=document.getElementById("postEditor");if(!m)return;m.classList.remove("hidden");const a=document.getElementById("postEditorAvatar");if(a&&currentUser?.uid){getUserProfile(currentUser.uid).then(u=>{if(u)setProfileImage("postEditorAvatar",u.avatarUrl,(u.name||"A")[0])}).catch(()=>{})}};
window.closePostEditor=()=>document.getElementById("postEditor")?.classList.add("hidden");
window.previewPostMedia=()=>{const input=document.getElementById("postMedia"),box=document.getElementById("postMediaPreview"),f=input?.files?.[0];if(!box)return;box.innerHTML="";if(!f){box.classList.add("hidden");return}const url=URL.createObjectURL(f),el=document.createElement(f.type.startsWith("video")?"video":"img");el.src=url;if(el.tagName==="VIDEO"){el.controls=true;el.muted=true;el.playsInline=true}box.appendChild(el);box.classList.remove("hidden")};
window.clearPostMedia=()=>{const i=document.getElementById("postMedia"),box=document.getElementById("postMediaPreview");if(i)i.value="";if(box){box.innerHTML="";box.classList.add("hidden")}};
window.previewPostStyle=()=>{const input=document.getElementById("postText"),preview=document.getElementById("postTextPreview");if(!preview)return;preview.textContent=input?.value||"معاينة النص";preview.style.background=document.getElementById("postBg")?.value||"#1A140F";preview.style.color=document.getElementById("postColor")?.value||"#F5E7C8";preview.style.fontFamily=document.getElementById("postFont")?.value||"inherit"};
window.publishPost=async()=>{const input=document.getElementById("postText"),media=document.getElementById("postMedia"),music=document.getElementById("postMusic"),text=input.value.trim(),file=media?.files?.[0]||null,musicFile=music?.files?.[0]||null;if(!text&&!file)return alert("اكتب نصًا أو اختر صورة/فيديو قبل النشر.");const btn=document.querySelector(".publish-btn"),progress=document.getElementById("postUploadProgress"),bar=document.getElementById("postUploadBar"),status=document.getElementById("postUploadStatus");try{if(btn)btn.disabled=true;if(progress)progress.classList.remove("hidden");if(status)status.textContent="جاري تجهيز المنشور…";let musicUrl="";if(musicFile){status.textContent="جاري رفع الموسيقى 0%";musicUrl=await uploadFile(musicFile,`postMusic/${currentUser.uid}`,(p)=>{if(status)status.textContent=`جاري رفع الموسيقى ${p}%`;if(bar)bar.style.width=`${p}%`})}const style={background:document.getElementById("postBg")?.value||"#1A140F",color:document.getElementById("postColor")?.value||"#F5E7C8",font:document.getElementById("postFont")?.value||"inherit"};if(file){status.textContent="جاري رفع صورة/فيديو 0%"}await createPost(currentUser,text,file,(p)=>{if(status)status.textContent=`جاري رفع الوسائط ${p}%`;if(bar)bar.style.width=`${p}%`},{musicUrl,style});input.value="";clearPostMedia();if(music){music.value="";document.getElementById("postMusicName")&&(document.getElementById("postMusicName").textContent="")}previewPostStyle();closePostEditor();alert("✓ تم نشر المنشور بنجاح")}catch(e){console.error(e);alert("تعذر نشر المنشور: "+(e?.message||"تحقق من Firebase Storage Rules والإنترنت."))}finally{if(btn)btn.disabled=false;if(progress)progress.classList.add("hidden");if(bar)bar.style.width="0%";if(status)status.textContent=""}};
let menuTarget=null;
window.closeActionMenu=()=>{document.getElementById("actionMenu")?.classList.add("hidden");menuTarget=null};
window.openActionMenu=(type,id,owner)=>{menuTarget={type,id,owner};const m=document.getElementById("actionMenu");if(!m)return;const title=document.getElementById("actionMenuTitle");const edit=document.getElementById("actionEdit");const del=document.getElementById("actionDelete");const report=document.getElementById("actionReport");title.textContent=type==="post"?"خيارات المنشور":"خيارات القصة";edit.classList.toggle("hidden",!owner);del.classList.toggle("hidden",!owner);report.classList.toggle("hidden",!!owner);m.classList.remove("hidden")};
window.actionEdit=async()=>{if(!menuTarget)return;const t=menuTarget.type;const id=menuTarget.id;if(t==="post"){const a=document.querySelector(`[data-post-id="${id}"] .post-content`)?.textContent||"";const n=prompt("تعديل المنشور:",a);if(n!==null&&n.trim()){try{await updatePostText(id,currentUser.uid,n.trim())}catch(e){alert(e.message||"تعذر تعديل المنشور.")}}}else{const s=window.__kronoStories?.find(x=>x.id===id);const n=prompt("تعديل نص القصة:",s?.text||"");if(n!==null){try{await updateStoryText(id,currentUser.uid,n.trim());closeStoryViewer()}catch(e){alert(e.message||"تعذر تعديل القصة.")}}}closeActionMenu()};
window.actionDelete=async()=>{if(!menuTarget)return;const t=menuTarget.type,id=menuTarget.id;if(!confirm(t==="post"?"هل تريد حذف هذا المنشور؟":"هل تريد حذف هذه القصة؟"))return;try{if(t==="post")await deletePost(id,currentUser.uid);else{await deleteStory(id,currentUser.uid);closeStoryViewer()}}catch(e){alert(e.message||"تعذر الحذف.")}closeActionMenu()};
window.actionReport=async()=>{if(!menuTarget)return;const reason=prompt("سبب الإبلاغ:","محتوى غير مناسب");if(reason===null)return;try{await reportContent(menuTarget.type,menuTarget.id,currentUser.uid,reason);alert("✓ تم إرسال البلاغ للمراجعة.")}catch(e){alert("تعذر إرسال البلاغ.")}closeActionMenu()};

function renderPostMedia(p){let h="";if(p.mediaUrl){h=p.mediaType==="video"?`<div class="post-media"><video src="${esc(p.mediaUrl)}" controls playsinline preload="metadata"></video></div>`:`<div class="post-media"><img src="${esc(p.mediaUrl)}" alt="وسائط المنشور" loading="lazy"></div>`}if(p.musicUrl)h+=`<div class="post-music"><span>${svgIcon("play")}</span><audio src="${esc(p.musicUrl)}" controls preload="none"></audio></div>`;return h}
function postActionIcon(name,label){return `<span class="action-icon">${svgIcon(name)}</span><span>${label}</span>`}
function renderPosts(posts){window.__kronoPosts=posts;setTimeout(()=>{renderShorts();renderWatch()},0);const c=document.getElementById("posts");if(!c)return;c.innerHTML="";if(!posts.length){c.innerHTML='<div class="post">لا توجد منشورات حتى الآن.</div>';return}posts.forEach(p=>{const owner=currentUser.uid===p.uid,a=document.createElement("article");a.className="post";a.dataset.postId=p.id;const st=p.style||{};const style=`background:${esc(st.background||"transparent")};color:${esc(st.color||"var(--text)")};font-family:${esc(st.font||"inherit")}`;a.innerHTML=`<div class="post-header"><div class="avatar" data-uid="${esc(p.uid)}">${esc((p.name||"A")[0])}</div><div class="post-user" data-uid="${esc(p.uid)}"><strong>${esc(p.name||"مستخدم Arlo")}${verifiedBadge(p.uid)}</strong><small class="muted">Arlo</small></div><button class="more-btn" title="خيارات" aria-label="خيارات" onclick="openActionMenu('post','${p.id}',${owner})">${svgIcon("more")}</button></div>${p.text?`<div class="post-content" style="${style}">${esc(p.text)}</div>`:""}${renderPostMedia(p)}<div class="post-stats"><span>${svgIcon("eye")} ${p.viewsCount||0}</span><span>${svgIcon("heart")} ${p.likesCount||0}</span><span>${svgIcon("comment")} ${p.commentsCount||0}</span></div><div class="post-actions"><div class="reaction-wrap"><button class="reaction-main" data-post="${p.id}" onclick="quickReaction('${p.id}')">${postActionIcon("heart","إعجاب")}</button><div class="reaction-picker" id="reaction-${p.id}">${REACTIONS.map(r=>`<button aria-label="${r.key}" onclick="reactToPost('${p.id}','${r.key}')">${r.icon}</button>`).join("")}</div></div><button onclick="toggleComments('${p.id}')">${postActionIcon("comment",`تعليق ${p.commentsCount||0}`)}</button><button onclick="savePost('${p.id}')">${postActionIcon("bookmark","حفظ")}</button><button onclick="sharePost('${p.id}',${JSON.stringify(p.text||"")})">${postActionIcon("share","مشاركة")}</button></div>${owner?`<div class="owner-insights"><button class="owner-insights-btn" onclick="showPostInsights('${p.id}')">${postActionIcon("eye","المشاهدون")}</button></div>`:""}<div id="commentsBox-${p.id}" class="comments-box hidden"><div id="commentsList-${p.id}"></div><div class="comment-input"><input id="commentInput-${p.id}" placeholder="اكتب تعليقك..." autocomplete="off"><button onclick="sendComment('${p.id}')">إرسال</button></div></div>`;a.querySelectorAll("[data-uid]").forEach(x=>{x.onclick=()=>openUserProfile(x.dataset.uid);x.setAttribute("role","button");x.setAttribute("tabindex","0")});c.appendChild(a);getMyReaction("post",p.id,currentUser.uid).then(r=>{if(r){const b=a.querySelector('.reaction-main');b.innerHTML=postActionIcon("heart","تفاعل");b.classList.add('active')}}).catch(()=>{});observePost(a,p.id)});enableLongPress()}
const REACTIONS=[{key:'like',icon:'👍'},{key:'love',icon:'❤️'},{key:'haha',icon:'😂'},{key:'wow',icon:'😮'},{key:'sad',icon:'😢'},{key:'angry',icon:'😡'}];
function observePost(el,id){if(!('IntersectionObserver' in window)){savePostView(id,currentUser.uid).catch(()=>{});return}const io=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){savePostView(id,currentUser.uid).catch(()=>{});io.disconnect()}})},{threshold:.55});io.observe(el)}
window.toggleReactionPicker=id=>document.getElementById(`reaction-${id}`)?.classList.toggle('show');
function enableLongPress(){document.querySelectorAll('.reaction-main').forEach(b=>{let timer;const id=b.dataset.post;const start=()=>{timer=setTimeout(()=>{document.getElementById(`reaction-${id}`)?.classList.add('show')},550)};const cancel=()=>clearTimeout(timer);b.addEventListener('pointerdown',start);b.addEventListener('pointerup',cancel);b.addEventListener('pointerleave',cancel);b.addEventListener('pointercancel',cancel)})}
window.quickReaction=async id=>reactToPost(id,'like');
window.reactToPost=async(id,reaction)=>{try{const r=await toggleReaction('post',id,currentUser.uid,reaction);const b=document.querySelector(`[data-post="${id}"] .reaction-main`);if(b){b.innerHTML=r.reaction?postActionIcon('heart','تفاعل'):postActionIcon('heart','إعجاب');b.classList.toggle('active',!!r.reaction)}document.getElementById(`reaction-${id}`)?.classList.remove('show')}catch(e){console.error(e);alert('تعذر تسجيل التفاعل.')}};
window.likePost=window.quickReaction;
window.toggleComments=id=>{const box=document.getElementById(`commentsBox-${id}`);if(!box)return;box.classList.toggle('hidden');if(!box.classList.contains('hidden')&&!commentListeners[id])commentListeners[id]=watchComments(id,cs=>{const l=document.getElementById(`commentsList-${id}`);if(l)l.innerHTML=cs.map(c=>`<div class="comment"><strong>${esc(c.name)}</strong><span>${esc(c.text)}</span></div>`).join('')})};
window.sendComment=async id=>{const i=document.getElementById(`commentInput-${id}`);if(!i)return;const t=i.value.trim();if(!t)return;try{await addComment(id,currentUser,t);i.value=''}catch(e){alert('تعذر إضافة التعليق.')}};
window.showPostInsights=async id=>{try{const x=await getPostInsights(id);const names=await Promise.all(x.views.map(v=>getUserProfile(v.uid)));const reacts=await Promise.all(x.reactions.map(v=>getUserProfile(v.uid)));alert(`👁️ المشاهدون: ${names.filter(Boolean).map(u=>u.name).join('، ')||'لا يوجد'}\n❤️ التفاعلات: ${reacts.filter(Boolean).map(u=>u.name).join('، ')||'لا يوجد'}`)}catch(e){alert('تعذر تحميل المشاهدين.')}};
window.savePost=id=>{let a=JSON.parse(localStorage.getItem('arloSaved')||'[]');if(!a.includes(id)){a.push(id);localStorage.setItem('arloSaved',JSON.stringify(a));alert('🔖 تم حفظ المنشور')}else alert('المنشور محفوظ بالفعل.')};
window.sharePost=async(id,text)=>{try{if(navigator.share)await navigator.share({title:'Arlo',text,url:location.href});else{await navigator.clipboard.writeText((text||'')+' '+location.href);alert('✓ تم نسخ المنشور.')}}catch{}};

function renderStories(stories){window.__kronoStories=stories;const c=document.getElementById("stories");c.innerHTML="";stories.slice(0,20).forEach(s=>{const d=document.createElement("div");d.className="story-card";d.innerHTML=`<div class="story-ring"><div class="story-avatar">${esc((s.name||"K")[0])}</div></div><small>${esc(s.name)}</small>`;d.onclick=()=>openStory(s);c.appendChild(d)})}
window.openStoryEditor=()=>document.getElementById("storyEditor").classList.remove("hidden");window.closeStoryEditor=()=>document.getElementById("storyEditor").classList.add("hidden");window.clearStoryEditor=()=>{document.getElementById("storyMedia").value="";document.getElementById("storyText").value="";document.getElementById("storyAudio").value="";document.getElementById("audioName").textContent="";document.getElementById("storyPreview").innerHTML="<span>المعاينة تظهر هنا</span>"};
function previewStory(){const f=document.getElementById("storyMedia").files[0],text=document.getElementById("storyText").value.trim(),p=document.getElementById("storyPreview");p.innerHTML="";if(f){const url=URL.createObjectURL(f),el=document.createElement(f.type.startsWith("video")?"video":"img");el.src=url;if(el.tagName==="VIDEO"){el.controls=true;el.muted=true}p.appendChild(el)}if(text){const t=document.createElement("div");t.className="story-overlay";t.textContent=text;p.appendChild(t)}if(!f&&!text)p.innerHTML="<span>المعاينة تظهر هنا</span>"}
document.getElementById("storyText")?.addEventListener("input",previewStory);
window.publishStory=async()=>{const f=document.getElementById("storyMedia").files[0],audio=document.getElementById("storyAudio").files[0],text=document.getElementById("storyText").value.trim();if(!f&&!text&&!audio)return alert("اكتب نصًا أو اختر صورة/فيديو أو أضف موسيقى للقصة.");try{const btn=document.querySelector("#storyEditor .primary-btn");if(btn){btn.disabled=true;btn.textContent="جاري الرفع 0%"}await createStory(currentUser,f,text,audio,p=>{if(btn)btn.textContent=`جاري الرفع ${p}%`});alert("✨ تم نشر القصة بنجاح");clearStoryEditor();closeStoryEditor()}catch(e){console.error(e);alert("تعذر نشر القصة: "+(e?.message||"تأكد من Firebase Storage Rules وFirestore Rules."))}finally{const btn=document.querySelector("#storyEditor .primary-btn");if(btn){btn.disabled=false;btn.textContent="نشر القصة"}}};
window.openStory=async s=>{try{await saveStoryView(s.id,currentUser.uid);const c=document.getElementById("storyViewerContent");c.innerHTML="";if(s.mediaUrl){const el=document.createElement(s.mediaType==="video"?"video":"img");el.src=s.mediaUrl;if(el.tagName==="VIDEO"){el.controls=true;el.playsInline=true;el.autoplay=false}c.appendChild(el)}if(s.text){const t=document.createElement("div");t.className="story-overlay";t.textContent=s.text;c.appendChild(t)}if(s.audioUrl){const a=document.createElement("audio");a.src=s.audioUrl;a.controls=true;a.autoplay=true;c.appendChild(a)}const owner=currentUser.uid===s.uid;const bar=document.createElement("div");bar.className="story-social";bar.innerHTML=`<div class="story-reaction-wrap"><button id="storyLikeBtn" onclick="reactToStory('${s.id}','like')">👍 إعجاب</button><div id="storyReactionPicker" class="reaction-picker">${REACTIONS.map(r=>`<button onclick="reactToStory('${s.id}','${r.key}')">${r.icon}</button>`).join('')}</div></div><span>👁️ ${s.viewsCount||0}</span><span>❤️ ${s.likesCount||0}</span>${owner?`<button onclick="showStoryInsights('${s.id}')">👤 من شاهدها</button>`:''}<button class="story-more" onclick="openActionMenu('story','${s.id}',${owner})">⋮</button>`;c.appendChild(bar);let storyTimer;const sb=document.getElementById('storyLikeBtn');sb?.addEventListener('pointerdown',()=>storyTimer=setTimeout(()=>document.getElementById('storyReactionPicker')?.classList.add('show'),550));['pointerup','pointerleave'].forEach(ev=>sb?.addEventListener(ev,()=>clearTimeout(storyTimer)));getMyReaction('story',s.id,currentUser.uid).then(r=>{if(r){const b=document.getElementById('storyLikeBtn');if(b)b.innerHTML=`<i class="ui-icon icon-heart"></i> تفاعل`}}).catch(()=>{});document.getElementById("storyViewer").classList.remove("hidden")}catch(e){alert('تعذر فتح القصة.')}};
window.reactToStory=async(id,reaction)=>{try{const r=await toggleReaction('story',id,currentUser.uid,reaction);const b=document.getElementById('storyLikeBtn');if(b)b.innerHTML=r.reaction?postActionIcon("heart","تفاعل"):postActionIcon("heart","إعجاب");}catch(e){alert('تعذر تسجيل التفاعل.')}};
window.showStoryInsights=async id=>{try{const x=await getStoryInsights(id);const names=await Promise.all(x.views.map(v=>getUserProfile(v.uid)));const reacts=await Promise.all(x.reactions.map(v=>getUserProfile(v.uid)));alert(`👁️ المشاهدات: ${names.filter(Boolean).map(u=>u.name).join('، ')||'لا يوجد'}\n❤️ التفاعلات: ${reacts.filter(Boolean).map(u=>u.name).join('، ')||'لا يوجد'}`)}catch(e){alert('تعذر تحميل الإحصائيات.')}};
window.closeStoryViewer=()=>document.getElementById("storyViewer").classList.add("hidden");

window.openUserProfile=async uid=>{if(uid===currentUser.uid)return openPage("profile");const u=await getUserProfile(uid);if(!u)return alert("لم يتم العثور على المستخدم.");selectedUser=u;const visible=document.querySelector(".page:not(.hidden)");lastPageBeforeUserProfile=visible?.id?.replace(/Page$/i,"")||"home";setProfileImage("otherPageAvatar",u.avatarUrl,(u.name||"K")[0]);const otherNameEl=document.getElementById("otherPageName");if(otherNameEl)otherNameEl.innerHTML=esc(u.name||"مستخدم Arlo")+verifiedBadge(u.uid);document.getElementById("otherPageUsername").textContent=u.username?`@${u.username}`:"";document.getElementById("otherPageBio").textContent=u.bio||"عضو في Arlo";document.getElementById("otherPageFriends").textContent=u.friendsCount||0;const emailEl=document.getElementById("otherPageEmail");if(emailEl)emailEl.textContent=u.publicEmail?(u.email||""):"";const birth=document.getElementById("otherPageBirth");if(birth)birth.textContent=u.birth?`🎂 ${u.birth}`:"";const cover=document.querySelector('#otherProfilePage .profile-cover');if(cover)cover.style.backgroundImage=u.coverUrl?`url("${esc(u.coverUrl)}")`:"";const b=document.getElementById("otherPageFriendButton");const fs=await getFriendStatus(currentUser.uid,u.uid);b.disabled=false;b.onclick=null;if(fs==="friends"){b.textContent="✓ أصدقاء";b.disabled=true}else if(fs==="sent"){b.textContent="✓ تم إرسال الطلب";b.disabled=true}else if(fs==="received"){b.textContent="✓ لديه طلب منك";b.disabled=true}else{b.textContent="➕ إضافة صديق";b.onclick=async()=>{try{await sendFriendRequest(currentUser,u.uid);b.textContent="✓ تم إرسال الطلب";b.disabled=true}catch(e){alert(e.message)}}}const fb=document.getElementById("otherPageFollowButton");if(fb){fb.disabled=false;fb.textContent=await isFollowing(currentUser.uid,u.uid)?"✓ متابَع":"＋ متابعة";fb.onclick=()=>toggleUserFollow(u.uid)};const list=document.getElementById("otherPagePostsList"),posts=(window.__kronoPosts||[]).filter(p=>p.uid===uid);list.innerHTML=posts.length?posts.map(p=>`<article class="post"><div class="post-header"><div class="avatar">${esc((p.name||"K")[0])}</div><div><strong>${esc(p.name||"مستخدم Arlo")}</strong><small class="muted">Arlo</small></div></div>${p.text?`<div class="post-content">${esc(p.text)}</div>`:""}${renderPostMedia(p)}<div class="post-stats"><span>👁️ ${p.viewsCount||0}</span><span>❤️ ${p.likesCount||0}</span><span>💬 ${p.commentsCount||0}</span></div></article>`).join(""):"<div class='post'>لا توجد منشورات ظاهرة لهذا الحساب حاليًا.</div>";document.getElementById("otherPagePosts").textContent=posts.length;document.getElementById("otherProfilePage").classList.remove("hidden");document.querySelectorAll(".page").forEach(x=>{if(x.id!=="otherProfilePage")x.classList.add("hidden")})};

async function loadExplore(users=null){users=users||window.__kronoUsers||await getUsers();const c=document.getElementById("exploreUsers");c.innerHTML=users.filter(u=>u.uid!==currentUser.uid).map(u=>`<div class="user-tile" data-uid="${esc(u.uid)}"><div class="avatar" style="margin:auto">${esc((u.name||"K")[0])}</div><b>${esc(u.name)}</b><small class="muted">@${esc(u.username||"")}</small></div>`).join("");c.querySelectorAll("[data-uid]").forEach(x=>x.onclick=()=>openUserProfile(x.dataset.uid))}
window.searchUsers=async value=>{const box=document.getElementById("searchResults");if(!value.trim()){box.classList.add("hidden");return}const users=await findUsers(value);box.innerHTML=users.map(u=>`<button type="button" class="user-row" data-uid="${esc(u.uid)}"><div class="avatar">${esc((u.name||"K")[0])}</div><div><b>${esc(u.name)}</b><small class="muted">@${esc(u.username||"")}</small></div></button>`).join("")||"لا توجد نتائج";box.classList.remove("hidden");box.querySelectorAll("[data-uid]").forEach(x=>x.onclick=()=>openUserProfile(x.dataset.uid))};
window.focusGlobalSearch=(value='')=>{const i=document.getElementById('globalSearch');if(!i)return;i.value=value;i.focus();if(value)searchUsers(value)};


function renderNotifications(r){const c=document.getElementById("notificationsList");if(!c)return;c.innerHTML=r.length?r.map(x=>`<div class="post" data-notification-id="${esc(x.id)}"><b>${esc(x.fromName)}</b> يريد إضافتك صديقًا.<div class="post-actions"><button onclick="answerRequest('${x.id}','${x.fromUid}',true)">قبول</button><button onclick="answerRequest('${x.id}','${x.fromUid}',false)">رفض</button></div></div>`).join(""):"<div class='post'>لا توجد إشعارات جديدة.</div>"}
async function loadNotifications(){if(unsubscribeRequests)return;const r=await getIncomingRequests(currentUser.uid);renderNotifications(r)}
window.answerRequest=async(id,from,ok)=>{await respondFriendRequest(id,from,currentUser.uid,ok);loadNotifications();currentProfile=await getUserProfile(currentUser.uid);fillProfile()};

async function openChat(u){if(!u)return;selectedChatUser=u;const page=document.getElementById("messagesPage");page?.classList.add("chat-open");document.getElementById("chatPanel").classList.remove("hidden");document.getElementById("chatEmptyState")?.classList.add("hidden");document.getElementById("chatName").textContent=u.name||"مستخدم Arlo";document.getElementById("chatStatus").textContent="متصل الآن";setProfileImage("chatAvatar",u.avatarUrl,(u.name||"A")[0]);document.getElementById("messagesList").innerHTML="<div class='muted center' style='padding:20px'>جارٍ تحميل المحادثة...</div>";if(!window.__kronoPopChat){history.pushState({kronoChat:true},"",location.pathname+location.search+"#messages/chat");window.__kronoPopChat=true}if(unsubscribeMessages)unsubscribeMessages();unsubscribeMessages=watchMessages(currentUser.uid,u.uid,ms=>{const c=document.getElementById("messagesList");c.innerHTML=ms.map(m=>{const mine=m.fromUid===currentUser.uid;const time=m.createdAt?.toDate?m.createdAt.toDate().toLocaleTimeString("ar-EG",{hour:"2-digit",minute:"2-digit"}):"";return `<div class="bubble-wrap ${mine?"mine":"theirs"}"><div class="bubble ${mine?"me":""}">${m.text?`<div class="bubble-text">${esc(m.text)}</div>`:""}${m.audioUrl?`<audio class="chat-audio" src="${esc(m.audioUrl)}" controls preload="none"></audio>`:""}${m.mediaUrl?`${m.mediaType==="image"?`<img class="chat-media" src="${esc(m.mediaUrl)}" alt="صورة مرسلة" loading="lazy">`:m.mediaType==="video"?`<video class="chat-media chat-video" src="${esc(m.mediaUrl)}" controls playsinline preload="metadata"></video>`:m.mediaType==="audio"?`<audio class="chat-audio" src="${esc(m.mediaUrl)}" controls preload="metadata"></audio>`:`<a class="chat-file" href="${esc(m.mediaUrl)}" target="_blank" rel="noopener">📎 ${esc(m.fileName||"ملف")}</a>`}`:""}<div class="bubble-meta"><span>${time}</span>${mine?`<span class="message-status">✓✓</span>`:""}</div></div></div>`}).join("");c.scrollTop=c.scrollHeight})}
window.openChat=openChat;window.closeChat=()=>{document.getElementById("chatPanel")?.classList.add("hidden");document.getElementById("messagesPage")?.classList.remove("chat-open");document.getElementById("chatEmptyState")?.classList.remove("hidden");closeChatInfo();selectedChatUser=null;window.__kronoPopChat=false;if(unsubscribeMessages){unsubscribeMessages();unsubscribeMessages=null}};
window.sendMessage=async()=>{const i=document.getElementById("messageInput"),t=i.value.trim();if(!t||!selectedChatUser)return;try{await sendMessage(currentUser,selectedChatUser.uid,t);i.value="";i.focus()}catch(e){console.error(e);alert("تعذر إرسال الرسالة: "+(e?.message||"تحقق من اتصال Firebase."))}};
let voiceRecorder=null,voiceChunks=[];window.toggleVoiceMessage=async()=>{if(voiceRecorder?.state==="recording"){voiceRecorder.stop();return}if(!selectedChatUser)return alert("افتح محادثة أولًا.");try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});voiceChunks=[];voiceRecorder=new MediaRecorder(stream);voiceRecorder.ondataavailable=e=>e.data.size&&voiceChunks.push(e.data);voiceRecorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(voiceChunks,{type:voiceRecorder.mimeType||"audio/webm"});try{const btn=document.getElementById("voiceMessageBtn");if(btn)btn.textContent="⏳";const file=new File([blob],`voice_${Date.now()}.webm`,{type:blob.type});const url=await uploadFile(file,`chatAudio/${currentUser.uid}`);await sendMessage(currentUser,selectedChatUser.uid,"",{audioUrl:url})}catch(e){alert("تعذر إرسال الرسالة الصوتية: "+(e.message||""))}finally{const btn=document.getElementById("voiceMessageBtn");if(btn)btn.textContent="🎙️"}};voiceRecorder.start();const btn=document.getElementById("voiceMessageBtn");if(btn)btn.textContent="⏹️"}catch(e){alert("لا يمكن استخدام الميكروفون. اسمح للمتصفح بالوصول إلى الميكروفون.")}};
let chatPeopleCache=[];
async function loadChatList(){const c=document.getElementById("chatList");if(!c)return;try{chatPeopleCache=await getChatPeople(currentUser.uid);renderChatList(chatPeopleCache)}catch(e){console.error(e);c.innerHTML="<div class='post'>تعذر تحميل قائمة الرسائل.</div>"}}
function renderChatList(users){const c=document.getElementById("chatList");if(!c)return;c.innerHTML=users.length?users.map(u=>`<button type="button" class="chat-row" data-chat-uid="${esc(u.uid||u.id)}"><div class="avatar">${esc((u.name||"K")[0])}</div><div class="chat-row-body"><div><b>${esc(u.name||"مستخدم Arlo")}</b><small>${esc(u.username?"@"+u.username:"متاح للمراسلة")}</small></div><span class="chat-row-time">•</span></div></button>`).join(""):"<div class='post'>لا يوجد مستخدمون آخرون حتى الآن.</div>";c.querySelectorAll("[data-chat-uid]").forEach(x=>x.onclick=()=>openChat(users.find(u=>(u.uid||u.id)===x.dataset.chatUid)))}
window.filterChatList=q=>{q=(q||'').trim().toLowerCase();renderChatList(chatPeopleCache.filter(u=>(u.name||'').toLowerCase().includes(q)||(u.username||'').toLowerCase().includes(q)))};
window.openChatInfo=()=>{if(!selectedChatUser)return;setProfileImage('chatInfoAvatar',selectedChatUser.avatarUrl,(selectedChatUser.name||'A')[0]);document.getElementById('chatInfoName').textContent=selectedChatUser.name||'مستخدم Arlo';document.getElementById('chatInfoUsername').textContent=selectedChatUser.username?`@${selectedChatUser.username}`:'مستخدم Arlo';document.getElementById('chatInfoModal')?.classList.remove('hidden')};
window.closeChatInfo=()=>document.getElementById('chatInfoModal')?.classList.add('hidden');
window.toggleChatMute=()=>{if(!selectedChatUser)return;const key='arloMute_'+selectedChatUser.uid;const on=localStorage.getItem(key)!=='true';localStorage.setItem(key,String(on));alert(on?'✓ تم كتم إشعارات المحادثة':'✓ تم إلغاء كتم المحادثة')};
const ARLO_EMOJIS=["😀","😃","😄","😁","😆","😅","😂","🤣","😊","😇","🙂","🙃","😉","😌","😍","🥰","😘","😗","😙","😚","😋","😛","😝","😜","🤪","🤨","🧐","🤓","😎","🤩","🥳","😏","😒","😞","😔","😟","😕","🙁","☹️","😣","😖","😫","😩","🥺","😢","😭","😤","😠","😡","🤬","🤯","😳","🥵","🥶","😱","😨","😰","😥","😓","🤗","🤔","🤭","🤫","🤥","😶","😐","😑","😬","🙄","😯","😦","😧","😮","😲","🥱","😴","🤤","😪","😵","🤐","🥴","🤢","🤮","🤧","😷","🤒","🤕","❤️","🧡","💛","💚","💙","💜","🖤","🤍","🤎","💔","❣️","💕","💞","💓","💗","💖","💘","💝","👍","👎","👏","🙌","🙏","💪","🔥","✨","🎉","💯","✅","❌","⭐","💡","🎵","🎂"];
function buildEmojiPanel(){const p=document.getElementById("chatEmojiPanel");if(!p||p.dataset.ready)return;if(p) p.innerHTML=ARLO_EMOJIS.map(e=>`<button type="button" class="emoji-item" onclick="insertChatEmoji('${e}')">${e}</button>`).join("");if(p)p.dataset.ready="1"}
window.toggleEmojiPanel=()=>{buildEmojiPanel();document.getElementById("chatAttachMenu")?.classList.add("hidden");document.getElementById("chatEmojiPanel")?.classList.toggle("hidden");document.getElementById("messageInput")?.focus()};
window.insertChatEmoji=e=>{const i=document.getElementById("messageInput");if(!i)return;const a=i.selectionStart??i.value.length,b=i.selectionEnd??i.value.length;i.value=i.value.slice(0,a)+e+i.value.slice(b);i.focus();i.setSelectionRange(a+e.length,a+e.length)};
window.toggleAttachMenu=()=>{document.getElementById("chatEmojiPanel")?.classList.add("hidden");document.getElementById("chatAttachMenu")?.classList.toggle("hidden")};
window.pickChatAttachment=type=>{const map={image:"chatImageInput",video:"chatVideoInput",audio:"chatAudioInput",file:"chatFileInput"};document.getElementById("chatAttachMenu")?.classList.add("hidden");document.getElementById(map[type])?.click()};
window.attachChatFile=async input=>{const f=input?.files?.[0];if(!f||!selectedChatUser)return;if(f.size>50*1024*1024){alert("الملف أكبر من 50MB.");input.value="";return}try{const url=await uploadFile(f,`chatMedia/${currentUser.uid}`);let type="file";if(f.type.startsWith("image/"))type="image";else if(f.type.startsWith("video/"))type="video";else if(f.type.startsWith("audio/"))type="audio";await sendMessage(currentUser,selectedChatUser.uid,"",{mediaUrl:url,mediaType:type,fileName:f.name})}catch(e){console.error(e);alert("تعذر إرسال الملف: "+(e?.message||"تحقق من Firebase Storage Rules."))}finally{input.value=""}};

window.openPage=page=>{document.body.classList.toggle("arlo-messages-view",page==="messages");if(page!=="messages")closeChat();document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));document.getElementById(page+"Page")?.classList.remove("hidden");document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.remove("active"));const activeMap={home:0,explore:1,messages:3,profile:4};if(activeMap[page]!==undefined)document.querySelectorAll(".bottom-nav button")[activeMap[page]]?.classList.add("active");if(page==="notifications")loadNotifications();if(page==="messages")loadChatList();if(page==="profile")showProfileTab("posts");if(page==="shorts")renderShorts();if(page==="watch")renderWatch();if(page==="channels")renderChannels();if(page==="communities")renderCommunities();applyDataSaverUI();window.scrollTo(0,0)};
window.toggleTheme=()=>{document.body.classList.toggle("dark");localStorage.setItem("kronoTheme",document.body.classList.contains("dark")?"dark":"light")};if(localStorage.getItem("kronoTheme")==="dark")document.body.classList.add("dark");
if(localStorage.getItem(KRONO_DATA_SAVER_KEY)===null)localStorage.setItem(KRONO_DATA_SAVER_KEY,"true");
document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll(".nav-svg[data-icon], .ui-icon[data-icon]").forEach(el=>{el.innerHTML=svgIcon(el.dataset.icon)});previewPostStyle();document.getElementById("messageInput")?.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage()}});document.getElementById("aiInput")?.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();askAI()}})});
window.editProfile=()=>{document.getElementById("editName").value=currentProfile.name||"";document.getElementById("editUsername").value=currentProfile.username||"";document.getElementById("editBio").value=currentProfile.bio||"";document.getElementById("editModal").classList.remove("hidden")};window.closeEdit=()=>document.getElementById("editModal").classList.add("hidden");window.saveProfile=async()=>{const data={name:document.getElementById("editName").value.trim(),username:document.getElementById("editUsername").value.trim().replace(/^@/,""),bio:document.getElementById("editBio").value.trim()};if(!data.name)return alert("اكتب الاسم.");await updateUserProfile(currentUser.uid,data);currentProfile=await getUserProfile(currentUser.uid);fillProfile();closeEdit()};
window.saveProfileMedia=async(type)=>{const input=document.getElementById(type==="avatar"?"profileAvatarFile":"profileCoverFile"),file=input?.files?.[0];if(!file)return;if(!file.type.startsWith("image/"))return alert("اختر صورة فقط.");if(file.size>15*1024*1024)return alert("الصورة أكبر من 15MB. اختر صورة أصغر.");const label=input.closest("label"),old=label?.textContent;try{if(label)label.textContent="جاري الرفع...";const url=await uploadProfileMedia(currentUser.uid,file,type,p=>{if(label)label.textContent=`جاري الرفع ${p}%`});await updateUserProfile(currentUser.uid,type==="avatar"?{avatarUrl:url}:{coverUrl:url});currentProfile=await getUserProfile(currentUser.uid);fillProfile();alert("✓ تم تحديث الصورة بنجاح")}catch(e){console.error(e);alert("تعذر رفع الصورة: "+(e.message||"تأكد من Firebase Storage Rules."))}finally{if(label)label.innerHTML=(type==="avatar"?'<span class="ui-icon icon-camera"></span> تغيير صورة الملف':'<span class="ui-icon icon-image"></span> صورة الغلاف')+`<input id="${type==="avatar"?"profileAvatarFile":"profileCoverFile"}" type="file" accept="image/*" onchange="saveProfileMedia('${type}')" hidden>`}};
window.showProfileTab=tab=>{const c=document.getElementById("profileContent");if(tab==="saved"){const ids=JSON.parse(localStorage.getItem("kronoSaved")||"[]");c.innerHTML=ids.length?`<div class="post">لديك ${ids.length} منشور محفوظ على هذا الجهاز.</div>`:"<div class='post'>لا توجد منشورات محفوظة.</div>"}else if(tab==="stories"){c.innerHTML="<div class='post'>قصصك تظهر في شريط القصص أعلى الرئيسية.</div>"}else{c.innerHTML="<div class='post'>منشوراتك تظهر في الرئيسية ويمكن تطوير تبويب الملف الشخصي لعرضها مباشرة.</div>"}};
// =====================================================
// KRONO v1.7 — SETTINGS
// =====================================================
window.openSettingsMenu=()=>document.getElementById("settingsMenu")?.classList.remove("hidden");
window.closeSettingsMenu=()=>document.getElementById("settingsMenu")?.classList.add("hidden");
window.closeSettingsSection=()=>document.getElementById("settingsSectionModal")?.classList.add("hidden");

const settingDefaults={
  notifications:true, storyReplies:true, messageRequests:true, publicStories:true,
  postComments:true, postMentions:true, activityStatus:true, dataSaver:true
};
function getSetting(k){const raw=localStorage.getItem("kronoSetting_"+k);return raw===null?settingDefaults[k]:raw==="true"}
function setSetting(k,v){localStorage.setItem("kronoSetting_"+k,String(v))}
function isVerified(uid=currentUser?.uid){return uid?localStorage.getItem("arloVerified_"+uid)==="true":false}
function verifiedBadge(uid=currentUser?.uid){return isVerified(uid)?'<span class="verified-badge" title="حساب موثّق" aria-label="حساب موثّق">✓</span>':""}
window.buyVerifiedBadge=()=>{if(!currentUser)return alert("سجّل الدخول أولًا.");if(isVerified())return alert("✓ حسابك موثّق بالفعل.");const ok=confirm("شراء علامة التوثيق الذهبية؟\n\nهذه نسخة تجريبية: لا يوجد دفع حقيقي متصل بعد.");if(!ok)return;localStorage.setItem("arloVerified_"+currentUser.uid,"true");fillProfile();alert("✓ تم تفعيل علامة التوثيق التجريبية على حسابك.")};


window.openSettingsSection=(section)=>{
  const titles={account:"الحساب وتسجيل الدخول",privacy:"الخصوصية",security:"الأمان وتسجيل الدخول",blocked:"الحظر",notifications:"الإشعارات",stories:"إعدادات القصص",posts:"إعدادات المنشورات",messages:"الرسائل والتعليقات",language:"اللغة",activity:"نشاطك",saved:"المحفوظات",verified:"توثيق الحساب",help:"المساعدة والإبلاغ",download:"تنزيل بياناتك",feed:"تفضيلات الصفحة الرئيسية",search:"البحث والاستكشاف",media:"الصور والفيديو والموسيقى",friends:"الأصدقاء وطلبات الصداقة",accessibility:"إمكانية الوصول",data:"استخدام البيانات"};
  const texts={account:"إدارة معلومات حسابك وتسجيل الدخول.",privacy:"تحكم في من يمكنه رؤية محتواك والتفاعل معك.",security:"إعدادات أمان الحساب وتسجيل الدخول.",blocked:"إدارة الحسابات التي لا تريد التفاعل معها.",notifications:"اختر الإشعارات التي تريد استقبالها.",stories:"تحكم في جمهور القصص والردود والتفاعلات.",posts:"تحكم في التعليقات والإشارات على منشوراتك.",messages:"إدارة الرسائل وطلبات المحادثة والتعليقات.",language:"اختيار لغة واجهة Arlo.",activity:"مراجعة نشاطك داخل التطبيق.",saved:"الوصول إلى المحتوى الذي حفظته.",verified:"شراء وإدارة علامة التوثيق الذهبية لحسابك.",help:"المساعدة والإبلاغ عن المشاكل والمحتوى.",download:"يمكنك لاحقًا ربط هذا الخيار بتصدير بيانات Firebase الخاصة بحسابك.",feed:"تحكم في طريقة عرض المحتوى والتنبيهات داخل الصفحة الرئيسية.",search:"تحكم في تجربة البحث والاستكشاف ونتائج الحسابات.",media:"إعدادات الوسائط والصوت. يدعم الإصدار الحالي رفع ملفات الوسائط التي يختارها المستخدم.",friends:"إدارة طلبات الصداقة والتفاعل مع الحسابات.",accessibility:"خيارات لتسهيل استخدام KRONO على الشاشات والأجهزة المختلفة.",data:"خيارات مرتبطة باستهلاك البيانات والتحميل."};
  const body=document.getElementById("settingsDetailBody");
  document.getElementById("settingsDetailTitle").textContent=titles[section]||"الإعدادات";
  document.getElementById("settingsDetailText").textContent=texts[section]||"";
  const toggle=(key,label)=>`<label class="setting-toggle"><span>${label}</span><input type="checkbox" ${getSetting(key)?"checked":""} onchange="setKronoSetting('${key}',this.checked)"><i></i></label>`;
  let html="";
  if(section==="notifications") html=toggle("notifications","🔔 إشعارات التطبيق");
  else if(section==="stories") html=toggle("publicStories","🌎 السماح للآخرين برؤية قصصي")+toggle("storyReplies","💬 السماح بالردود على القصص");
  else if(section==="posts") html=toggle("postComments","💬 السماح بالتعليقات")+toggle("postMentions","🏷️ السماح بالإشارات");
  else if(section==="messages") html=toggle("messageRequests","📩 استقبال طلبات الرسائل")+toggle("activityStatus","🟢 إظهار حالة النشاط");
  else if(section==="privacy") html=toggle("publicStories","🌎 المحتوى العام")+toggle("activityStatus","🟢 حالة النشاط")+toggle("publicEmail","📧 إظهار بريدي الإلكتروني للآخرين");
  else if(section==="language") html=`<button class="setting-btn active">🇪🇬 العربية</button><button class="setting-btn" onclick="alert('إضافة لغات أخرى في إصدار لاحق.')">🌐 إضافة لغة</button>`;
  else if(section==="saved") html=`<button class="setting-btn" onclick="openPage('profile');closeSettingsSection()">🔖 فتح المحفوظات</button>`;
  else if(section==="verified") html=`<div class="verified-card"><h3>✓ توثيق حساب Arlo</h3><p>${isVerified()?"حسابك يحمل علامة التوثيق الذهبية بالفعل.":"أضف علامة التوثيق الذهبية إلى حسابك لتظهر بجانب اسمك في الملف الشخصي والمنشورات."}</p><button class="verified-buy ${isVerified()?"owned":""}" ${isVerified()?"disabled":"onclick=\"buyVerifiedBadge()\""}>${isVerified()?"✓ الحساب موثّق":"⭐ شراء علامة التوثيق"}</button></div>`;
  else if(section==="help") html=`<button class="setting-btn" onclick="alert('للتجربة: استخدم خيار الإبلاغ من ⋮ على أي محتوى.')">⚠️ كيفية الإبلاغ</button><button class="setting-btn" onclick="alert('مركز مساعدة Arlo قيد التجهيز.')">❓ مركز المساعدة</button>`;
  else if(section==="download") html=`<button class="setting-btn" onclick="alert('تصدير البيانات يحتاج ربطًا إضافيًا بـFirebase Functions.')">📥 طلب نسخة من بياناتي</button>`;
  else if(section==="feed") html=toggle("postComments","💬 إظهار التفاعل على المنشورات")+toggle("notifications","🔔 تنبيهات الخلاصة");
  else if(section==="search") html=toggle("publicStories","🌎 السماح باكتشاف الحساب العام")+`<button class="setting-btn" onclick="openPage('explore');closeSettingsSection()">🔎 فتح الاستكشاف</button>`;
  else if(section==="media") html=`<p class="empty-settings">🎵 الموسيقى في V1.8 تعمل عبر ملفات الصوت التي يختارها المستخدم. إضافة كتالوج أغاني عالمي تحتاج خدمة موسيقى مرخّصة ومتكاملة مع Firebase.</p>`;
  else if(section==="friends") html=`<button class="setting-btn" onclick="openPage('notifications');closeSettingsSection()">👥 إدارة طلبات الصداقة</button>`;
  else if(section==="accessibility") html=toggle("activityStatus","🟢 تقليل عناصر الحركة")+`<button class="setting-btn" onclick="alert('سيتم توسيع خيارات الوصول في إصدار لاحق.')">⚙️ المزيد</button>`;
  else if(section==="data") html=`${toggle("dataSaver","📉 تفعيل وضع توفير البيانات")}<p class="empty-settings">عند تفعيله، KRONO يقلل تحميل الخلاصة، يمنع التحميل التلقائي للفيديو، يضغط الصور الكبيرة، ويحمّل الوسائط عند الحاجة.</p>`;
  else if(section==="blocked") html=`<p class="empty-settings">لا توجد حسابات محظورة حاليًا.</p>`;
  else if(section==="activity") html=`<p class="empty-settings">سجل النشاط التفصيلي سيتم ربطه ببيانات Firebase في الإصدار القادم.</p>`;
  else if(section==="account"||section==="security") html=`<button class="setting-btn" onclick="editProfile();closeSettingsSection()">✏️ تعديل بيانات الملف</button><button class="setting-btn" onclick="alert('تغيير كلمة السر متاح عبر Firebase Authentication.')">🔑 تغيير كلمة السر</button>`;
  else html=`<p class="empty-settings">هذه الصفحة جاهزة للتوسع وربط إعداداتها مع Firebase.</p>`;
  body.innerHTML=html;
  document.getElementById("settingsSectionModal").classList.remove("hidden");
};
window.setKronoSetting=async(k,v)=>{setSetting(k,v);if(k==="dataSaver")localStorage.setItem(KRONO_DATA_SAVER_KEY,String(v));if(k==="publicEmail"){try{await updateUserProfile(currentUser.uid,{publicEmail:!!v});currentProfile=await getUserProfile(currentUser.uid)}catch(e){alert("تعذر حفظ خصوصية البريد الإلكتروني.");return}}applyDataSaverUI();alert(v?"✓ تم تفعيل الإعداد":"✓ تم إيقاف الإعداد")};
window.requestDeleteAccount=async()=>{if(!currentUser)return;const ok=confirm("⚠️ سيتم حذف حساب KRONO وبيانات ملفك من Firebase وتسجيل خروجك. هذا الإجراء لا يمكن التراجع عنه. هل تريد المتابعة؟");if(!ok)return;const again=prompt("للتأكيد اكتب: حذف الحساب");if(again!=="حذف الحساب")return alert("تم إلغاء العملية.");try{accountDeletionInProgress=true;await deleteOwnAccount();accountDeletionInProgress=false;alert("✓ تم حذف حسابك بنجاح.");await logoutUser()}catch(e){accountDeletionInProgress=false;const c=e?.code||"";if(c.includes("requires-recent-login"))alert("لأمان حسابك، سجّل الدخول مرة أخرى ثم أعد محاولة حذف الحساب.");else alert("تعذر حذف الحساب: "+(e?.message||"حدث خطأ."))}};

window.askAI=async()=>{const i=document.getElementById("aiInput"),t=i.value.trim();if(!t)return;const c=document.getElementById("aiMessages");c.innerHTML+=`<div class="ai-msg user-ai-msg">${esc(t)}</div>`;i.value="";const lower=t.toLowerCase();let reply="أقدر أساعدك في Arlo: النشر، القصص، الرسائل، الملف الشخصي، الخصوصية، والإعدادات. اكتب سؤالك بشكل أوضح.";if(/سلام|اهلا|أهلا|hello|hi/.test(lower))reply="أهلًا بك 👋 أنا مساعد Arlo. اسألني عن استخدام التطبيق أو مشكلاته.";else if(/نشر|صورة|فيديو|story|ستوري|قصة/.test(lower))reply="للنشر: اختر النص أو الصورة أو الفيديو ثم اضغط نشر. إذا كان الملف كبيرًا سيظهر لك السبب بدل أن يظل التطبيق على جاري النشر.";else if(/رسائل|محادث|واتساب|ماسنجر/.test(lower))reply="من الرسائل اضغط على اسم الشخص لفتح شاشة محادثة مستقلة، ومعها أزرار الاتصال الصوتي والفيديو.";else if(/بروفايل|ملف شخصي|صورة.*خلف|غلاف/.test(lower))reply="من الملف الشخصي يمكنك تغيير صورة الحساب وصورة الغلاف، وتاريخ الميلاد يظهر حسب إعدادات الخصوصية.";else if(/ايميل|بريد|خصوصية/.test(lower))reply="البريد الإلكتروني مخفي افتراضيًا ويمكنك إظهاره أو إخفاؤه من إعدادات الخصوصية.";else if(/رجوع|back|اندرويد/.test(lower))reply="زر الرجوع في أندرويد يرجع للشاشة السابقة أو يغلق المحادثة/القصة قبل الخروج من التطبيق.";c.innerHTML+=`<div class="ai-msg">🤖 AI Arlo: ${esc(reply)}</div>`;c.scrollTop=c.scrollHeight};
window.logout=async()=>{try{[unsubscribePosts,unsubscribeStories,unsubscribeMessages,unsubscribeUsers,unsubscribeRequests,unsubscribeChannels,unsubscribeCommunities].forEach(fn=>{try{fn?.()}catch{}});unsubscribePosts=unsubscribeStories=unsubscribeMessages=unsubscribeUsers=unsubscribeRequests=unsubscribeChannels=unsubscribeCommunities=null;await logoutUser()}catch(e){console.error(e)}};
function firebaseError(e){const c=e?.code||"";if(c.includes("email-already-in-use"))return"يوجد حساب بالفعل بهذا البريد. استخدم تسجيل الدخول.";if(c.includes("invalid-credential"))return"البريد أو كلمة السر غير صحيحة.";if(c.includes("weak-password"))return"كلمة السر ضعيفة.";if(c.includes("invalid-email"))return"البريد الإلكتروني غير صحيح.";return e?.message||"حدث خطأ غير متوقع."}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}


// KRONO V1.8 — small UX safeguards; all V1.7 functionality remains intact.
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeActionMenu();closeSettingsMenu();closeSettingsSection();closeStoryEditor();closeStoryViewer();closeUserProfile();closeEdit()}});
document.addEventListener('click',e=>{if(!e.target.closest('.reaction-wrap')&&!e.target.closest('.reaction-picker'))document.querySelectorAll('.reaction-picker.show').forEach(x=>x.classList.remove('show'))});

// KRONO V3 navigation + mobile back safety
let kronoPageHistory=[];
const originalOpenPage=window.openPage;
window.openPage=(page,fromPop=false)=>{const current=document.querySelector('.page:not(.hidden)')?.id?.replace(/Page$/i,'');if(!fromPop&&current&&current!==page){kronoPageHistory.push(current);history.pushState({kronoPage:page},"",location.pathname+location.search+"#"+page)}originalOpenPage(page)};
window.addEventListener('popstate',()=>{if(window.__kronoPopChat||!document.getElementById('chatPanel')?.classList.contains('hidden')){closeChat();return}if(!document.getElementById('storyViewer')?.classList.contains('hidden')){closeStoryViewer();return}if(!document.getElementById('settingsMenu')?.classList.contains('hidden')){closeSettingsMenu();return}const prev=kronoPageHistory.pop();if(prev){originalOpenPage(prev)}else{history.pushState({kronoPage:'home-guard'},"",location.pathname+location.search+"#home");originalOpenPage('home')}});
window.addEventListener('DOMContentLoaded',()=>{if(!history.state?.kronoPage){history.replaceState({kronoPage:'home'},"",location.pathname+location.search+"#home");history.pushState({kronoPage:'home-guard'},"",location.pathname+location.search+"#home");}});
document.addEventListener('click',e=>{if(e.target.closest('a[href]'))return;});

// KRONO V3 — notifications + call UI helpers
window.enableKronoNotifications=async()=>{if(!('Notification' in window))return alert('هذا المتصفح لا يدعم إشعارات الجهاز.');const p=await Notification.requestPermission();alert(p==='granted'?'✓ تم تفعيل إشعارات الجهاز':'لم يتم السماح بالإشعارات.')};
window.startVideoCall=()=>{document.getElementById('callTitle').textContent=`📹 مكالمة فيديو مع ${selectedChatUser?.name||'مستخدم Arlo'}`;document.getElementById('callModal').classList.remove('hidden')};
window.startVoiceCall=()=>{document.getElementById('callTitle').textContent=`📞 مكالمة صوتية مع ${selectedChatUser?.name||'مستخدم Arlo'}`;document.getElementById('callModal').classList.remove('hidden')};
window.closeCallModal=()=>document.getElementById('callModal')?.classList.add('hidden');
